application:
    keycrypt:
        value: szeptySzeptuna
spring:
    datasource:
        url: jdbc:h2:file:./h2db/healthcheck
        username: sa
        password: sa
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /h2c
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    cache:
        jcache:
            config: classpath:ehcache.xml
    task:
        scheduling:
            pool:
                size: 10
    security:
        user:
            name: admin
            password: admin
            roles: USER
