INSERT INTO SERVICE_URL(URL_ADDRESS,HIT_INTERVAL_IN_MINUTES,RESPONSE_TYPE) VALUES ('https://gis.piaseczno.pl/public/api/health',30,'XML');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (1,200,'<Health>Ok</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (1,200,'<Health>Ok</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (1,200,'<Health>Ok</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (1,200,'<Health>Ok</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (1,406,'<Health>DB ERROR</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (1,406,'<Health>DB ERROR</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (1,406,'<Health>DB ERROR</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (1,406,'<Health>DB ERROR</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (1,406,'<Health>DB ERROR</Health>',now());


INSERT INTO SERVICE_URL(URL_ADDRESS,HIT_INTERVAL_IN_MINUTES,RESPONSE_TYPE) VALUES ('https://mpzp.gorakalwaria.pl/api/health',30,'XML');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (2,200,'<Health>Ok</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (2,200,'<Health>Ok</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (2,200,'<Health>Ok</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (2,200,'<Health>Ok</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (2,406,'<Health>DB ERROR</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (2,406,'<Health>DB ERROR</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (2,406,'<Health>DB ERROR</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (2,406,'<Health>DB ERROR</Health>',now());
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY,CREATED) VALUES (2,406,'<Health>DB ERROR</Health>',now());

INSERT INTO SERVICE_URL(URL_ADDRESS,HIT_INTERVAL_IN_MINUTES,RESPONSE_TYPE) VALUES ('http://sip.spytkowice.pl/api/health',30,'JSON');
INSERT INTO SERVICE_URL(URL_ADDRESS,HIT_INTERVAL_IN_MINUTES,RESPONSE_TYPE) VALUES ('http://sip.umciechanow.pl/api/health',30,'XML');
