INSERT INTO SERVICE_URL(ID,URL_ADDRESS,HIT_INTERVAL_IN_MINUTES) VALUES (0,'https://gis.piaseczno.pl/public/api/health',30);
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (0,200,'<Health>Ok</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (0,200,'<Health>Ok</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (0,200,'<Health>Ok</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (0,200,'<Health>Ok</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (0,406,'<Health>DB ERROR</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (0,406,'<Health>DB ERROR</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (0,406,'<Health>DB ERROR</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (0,406,'<Health>DB ERROR</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (0,406,'<Health>DB ERROR</Health>');


INSERT INTO SERVICE_URL(ID,URL_ADDRESS,HIT_INTERVAL_IN_MINUTES) VALUES (1,'https://mpzp.gorakalwaria.pl/api/health',30);
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (1,200,'<Health>Ok</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (1,200,'<Health>Ok</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (1,200,'<Health>Ok</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (1,200,'<Health>Ok</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (1,406,'<Health>DB ERROR</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (1,406,'<Health>DB ERROR</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (1,406,'<Health>DB ERROR</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (1,406,'<Health>DB ERROR</Health>');
INSERT INTO HIT_LOG(SERVICE_URL_ID ,RESPONSE_STATUS,RESPONSE_BODY) VALUES (1,406,'<Health>DB ERROR</Health>');

INSERT INTO SERVICE_URL(ID,URL_ADDRESS,HIT_INTERVAL_IN_MINUTES) VALUES (2,'http://sip.spytkowice.pl/api/health',30);
INSERT INTO SERVICE_URL(ID,URL_ADDRESS,HIT_INTERVAL_IN_MINUTES) VALUES (3,'http://sip.umciechanow.pl/api/health',30);
